spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=Ankit123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8083